image: golang:1.23

pipelines:
  default:
    - parallel:
      - step: 
          name: Test and build
          script:
            - mkdir test-reports
            - go mod download
            - go build -v ./...
            - go test -v ./...
      - step:
          name: Lint code
          image: golangci/golangci-lint:v1.62.2
          script:
            - golangci-lint run -v